serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "${karpenter_role_arn}"

settings:
  clusterName: "${cluster_name}"
  clusterEndpoint: "${cluster_endpoint}"

controller:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi